/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.deu.intsuperior.vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ec.edu.intsuperior.modelo.Clientes;
import ec.edu.intsuperior.modelo.DetalleFactura;
import ec.edu.intsuperior.modelo.Encabezado;
import ec.edu.intsuperior.modelo.Facturacion;
import ec.edu.intsuperior.modelo.Inventario;
import ec.edu.intsuperior.modelo.usuarios;
import ec.edu.intsuperior.modelo.Productos;
import static ec.deu.intsuperior.vista.jifrmClientess.rs;
import static ec.deu.intsuperior.vista.jifrmUsuarios.fechaActual;

/**
 *
 * @author Usuario
 */
public class jifrmFacturacion extends javax.swing.JInternalFrame {

    
    
     String titulosClientes[] = {"idCliente", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono", "Direccion"};

    DefaultTableModel dtmClientes = new DefaultTableModel(null, titulosClientes) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    
     String titulosInventrarioProd[] = {"IdInventario", "Descripcion", "Codigo", "Unidad de Medida", "Stock", "Precio"};

    DefaultTableModel dtmInventarioProd = new DefaultTableModel(null, titulosInventrarioProd) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

   
     String titulosDetalleFactura[] = {"Num","Producto", "Cantidad", "Precio","Stock","SubTotal","Iva", "Valor Total"};

    DefaultTableModel dtmDetalleFactura = new DefaultTableModel(null, titulosDetalleFactura) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
      String titulosFactura[] = {"IdEncabezado", "IdClientes","Apellido","Nombre", "IdUsuario", "Numero Factura", "Fecha", "Total"};

    DefaultTableModel dtmFactura = new DefaultTableModel(null, titulosFactura) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    
    
 double subTotal;
    double precio;
    int cantidad;
    int idInventario;
    
    
    String criterio, busqueda, strCodigo;
//    Integer busquedaInt;
    static ResultSet rs = null;
    Clientes cli = new Clientes();
    Inventario inv= new Inventario();
    Productos prod=new Productos();
    DetalleFactura det=new DetalleFactura();
    usuarios u = new usuarios();
    Facturacion fac=new Facturacion();
    Encabezado enc=new Encabezado();
    public jifrmFacturacion() {
        initComponents();
        generarSerie();
        SerieNumFactura();
         rbtnIdEncabezado.setSelected(true);
                 buscarFactura();
         rbtnIdCliente.setSelected(true);
         buscarCliente();
           rbtnIdInventario.setSelected(true);
          buscarInventrarioProducto();
          habilitarBotonesInicio();
    }
    
    
  public jifrmFacturacion(usuarios usu) {
        initComponents();
        generarSerie();
        SerieNumFactura();
        rbtnIdEncabezado.setSelected(true);
        buscarFactura();
         lblFechaActual.setText(fechaActual());
         rbtnIdCliente.setSelected(true);
         buscarCliente();
         rbtnIdInventario.setSelected(true);
          buscarInventrarioProducto();
          lblUsuario.setText(usu.getIdUsuario().toString());
       lblUsuarioDatos.setText(usu.getUsuUsuario());
        u=usu;
        tblDetalleFactura.setModel(dtmDetalleFactura);
        String tituloFactura[] = {"Id Inventario","Producto","Codigo", "Cantidad", "Precio","Stock","SubTotal","Iva", "Valor Total"};
        dtmDetalleFactura.setColumnIdentifiers(tituloFactura);
        tblDetalleFactura.getColumnModel().getColumn(0).setPreferredWidth(200);
        habilitarBotonesInicio();
    }
  
    public static String fechaActual(){
    
    Date fecha=new Date();
    SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy-MM-dd");
    
    return formatoFecha.format(fecha);
    
}
     public Boolean validar(){
        Boolean b=true;
        return b;
    }
       public Boolean validarDetalle(){
        Boolean b=true;
        return b;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngClientes = new javax.swing.ButtonGroup();
        rbtngProductosInventario = new javax.swing.ButtonGroup();
        rbtngFactura = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnConsumisor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCorreo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        pFormularioDatos = new javax.swing.JPanel();
        lblUsuarioDatos = new javax.swing.JLabel();
        txtNombreCli = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblIdClientess = new javax.swing.JLabel();
        pFormularioProduc = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDetalleFactura = new javax.swing.JTable();
        lblIdInventario = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnEliminarDet = new javax.swing.JButton();
        lblFechaActual = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblIdEncabezado = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rbtnIdEncabezado = new javax.swing.JRadioButton();
        rbtnCliente = new javax.swing.JRadioButton();
        rbtnNumeroFactu = new javax.swing.JRadioButton();
        txtBuscarFactura = new javax.swing.JTextField();
        lblTotalFactura = new javax.swing.JLabel();
        rbtnApellidos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbtnIdCliente = new javax.swing.JRadioButton();
        rbtnApellido = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnCedula = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        lblTotalRegistros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rbtnIdInventario = new javax.swing.JRadioButton();
        rbtnDescripcion = new javax.swing.JRadioButton();
        rbtnCodigo = new javax.swing.JRadioButton();
        txtBuscarInventarioProd = new javax.swing.JTextField();
        lblTotalRegistrosPro = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductosInventario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jToolBar1.setBackground(new java.awt.Color(255, 153, 153));
        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        jLabel1.setText("    ");
        jToolBar1.add(jLabel1);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        jLabel2.setText("   ");
        jToolBar1.add(jLabel2);

        jLabel3.setText("   ");
        jToolBar1.add(jLabel3);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarmmmmmm.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        jLabel4.setText("       ");
        jToolBar1.add(jLabel4);

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anular factura.png"))); // NOI18N
        btnAnular.setText("Anular Factura");
        btnAnular.setFocusable(false);
        btnAnular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnular);

        jLabel5.setText("      ");
        jToolBar1.add(jLabel5);

        btnConsumisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consumidor final.png"))); // NOI18N
        btnConsumisor.setText("Consumidor Final");
        btnConsumisor.setFocusable(false);
        btnConsumisor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsumisor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsumisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumisorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsumisor);

        jLabel8.setText("     ");
        jToolBar1.add(jLabel8);

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vender.png"))); // NOI18N
        btnVender.setText("Vender");
        btnVender.setFocusable(false);
        btnVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVender);

        jLabel9.setText("     ");
        jToolBar1.add(jLabel9);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnImprimir);

        jLabel7.setText("     ");
        jToolBar1.add(jLabel7);

        btnCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviar al correo.png"))); // NOI18N
        btnCorreo.setText("Enviar al correo");
        btnCorreo.setFocusable(false);
        btnCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorreo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCorreo);

        jLabel6.setText("     ");
        jToolBar1.add(jLabel6);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirrrrr.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        pFormularioDatos.setBackground(new java.awt.Color(153, 153, 153));

        lblUsuarioDatos.setBackground(new java.awt.Color(255, 204, 153));
        lblUsuarioDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Usuario"));
        lblUsuarioDatos.setOpaque(true);

        txtNombreCli.setBackground(new java.awt.Color(255, 153, 153));
        txtNombreCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        txtCedula.setBackground(new java.awt.Color(255, 153, 153));
        txtCedula.setBorder(javax.swing.BorderFactory.createTitledBorder("Cedula"));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(255, 153, 153));
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));

        txtTelefono.setBackground(new java.awt.Color(255, 153, 153));
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        txtDireccion.setBackground(new java.awt.Color(255, 153, 153));
        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));

        lblIdClientess.setBackground(new java.awt.Color(255, 153, 153));
        lblIdClientess.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Cliente"));
        lblIdClientess.setOpaque(true);

        pFormularioProduc.setBackground(new java.awt.Color(51, 153, 255));
        pFormularioProduc.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        lblProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));
        lblProducto.setOpaque(true);

        lblCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        lblCodigo.setOpaque(true);

        lblPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));
        lblPrecio.setOpaque(true);

        lblSub.setBorder(javax.swing.BorderFactory.createTitledBorder("SubTotal"));
        lblSub.setOpaque(true);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        tblDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblDetalleFactura);

        lblIdInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Inventario"));

        lblStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));
        lblStock.setOpaque(true);

        btnEliminarDet.setText("Eliminar");
        btnEliminarDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormularioProducLayout = new javax.swing.GroupLayout(pFormularioProduc);
        pFormularioProduc.setLayout(pFormularioProducLayout);
        pFormularioProducLayout.setHorizontalGroup(
            pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioProducLayout.createSequentialGroup()
                .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioProducLayout.createSequentialGroup()
                        .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFormularioProducLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pFormularioProducLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(lblSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 55, Short.MAX_VALUE)
                        .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIdInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnEliminarDet))
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addContainerGap())
        );
        pFormularioProducLayout.setVerticalGroup(
            pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioProducLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIdInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioProducLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pFormularioProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnEliminarDet))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(txtCantidad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblFechaActual.setBackground(new java.awt.Color(204, 255, 204));
        lblFechaActual.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Venta"));
        lblFechaActual.setOpaque(true);

        lblUsuario.setBackground(new java.awt.Color(255, 204, 153));
        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Usuario"));
        lblUsuario.setOpaque(true);

        lblIdEncabezado.setBackground(new java.awt.Color(255, 204, 255));
        lblIdEncabezado.setBorder(javax.swing.BorderFactory.createTitledBorder("IdEncabezado"));
        lblIdEncabezado.setOpaque(true);

        lblNumeroFactura.setBackground(new java.awt.Color(204, 255, 204));
        lblNumeroFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de Factura"));
        lblNumeroFactura.setOpaque(true);

        lblSubtotal.setBackground(new java.awt.Color(153, 204, 255));
        lblSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder("SubTotal"));
        lblSubtotal.setOpaque(true);

        lblIva.setBackground(new java.awt.Color(153, 204, 255));
        lblIva.setBorder(javax.swing.BorderFactory.createTitledBorder("IVA"));
        lblIva.setOpaque(true);

        lblTotal.setBackground(new java.awt.Color(153, 204, 255));
        lblTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total a Pagar"));
        lblTotal.setOpaque(true);

        javax.swing.GroupLayout pFormularioDatosLayout = new javax.swing.GroupLayout(pFormularioDatos);
        pFormularioDatos.setLayout(pFormularioDatosLayout);
        pFormularioDatosLayout.setHorizontalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblUsuarioDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                                .addComponent(lblIdClientess, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIdEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioDatosLayout.createSequentialGroup()
                        .addComponent(pFormularioProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(lblIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioDatosLayout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        pFormularioDatosLayout.setVerticalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdClientess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pFormularioProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addComponent(lblIdEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuarioDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIva, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tbDatos.addTab("Formulario Detalle", pFormularioDatos);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        rbtngFactura.add(rbtnIdEncabezado);
        rbtnIdEncabezado.setText("IdEncabezado");

        rbtngFactura.add(rbtnCliente);
        rbtnCliente.setText("IdCliente");

        rbtngFactura.add(rbtnNumeroFactu);
        rbtnNumeroFactu.setText("NumeroFactura");

        txtBuscarFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese texto de busqueda"));
        txtBuscarFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarFacturaKeyReleased(evt);
            }
        });

        lblTotalFactura.setBackground(new java.awt.Color(204, 204, 255));
        lblTotalFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Registros"));
        lblTotalFactura.setOpaque(true);

        rbtnApellidos.setText("Apellido");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbtnIdEncabezado)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCliente)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNumeroFactu)))
                .addGap(62, 62, 62)
                .addComponent(lblTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNumeroFactu)
                    .addComponent(rbtnCliente)
                    .addComponent(rbtnIdEncabezado)
                    .addComponent(rbtnApellidos))
                .addGap(23, 23, 23)
                .addComponent(txtBuscarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFactura);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Factura", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        rbtngClientes.add(rbtnIdCliente);
        rbtnIdCliente.setText("Id Cliente");

        rbtngClientes.add(rbtnApellido);
        rbtnApellido.setText("Apellido");

        rbtngClientes.add(rbtnNombre);
        rbtnNombre.setText("Nombre");

        rbtngClientes.add(rbtnCedula);
        rbtnCedula.setText("Cedula");

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Texto de Busqueda"));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        lblTotalRegistros.setBackground(new java.awt.Color(153, 255, 153));
        lblTotalRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Registros"));
        lblTotalRegistros.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnIdCliente)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnApellido)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCedula))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153)
                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnIdCliente)
                            .addComponent(rbtnApellido)
                            .addComponent(rbtnNombre)
                            .addComponent(rbtnCedula))
                        .addGap(16, 16, 16)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Cliente", jPanel3);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        rbtngProductosInventario.add(rbtnIdInventario);
        rbtnIdInventario.setText("IdInventario");

        rbtngProductosInventario.add(rbtnDescripcion);
        rbtnDescripcion.setText("Descripcion");

        rbtngProductosInventario.add(rbtnCodigo);
        rbtnCodigo.setText("Codigo");

        txtBuscarInventarioProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Criterio de Busqueda"));
        txtBuscarInventarioProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarInventarioProdKeyReleased(evt);
            }
        });

        lblTotalRegistrosPro.setBackground(new java.awt.Color(153, 255, 153));
        lblTotalRegistrosPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Registros"));
        lblTotalRegistrosPro.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbtnIdInventario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCodigo))
                    .addComponent(txtBuscarInventarioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(lblTotalRegistrosPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTotalRegistrosPro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnIdInventario)
                            .addComponent(rbtnDescripcion)
                            .addComponent(rbtnCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarInventarioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tblProductosInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductosInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosInventarioMouseClicked(evt);
            }
        });
        tblProductosInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProductosInventarioKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblProductosInventario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.addTab("Buscar Producto Inventario", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbDatos))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(tbDatos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscarCliente();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
       
          cargarDatosFormulario("cargarDatos");
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }

        
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblProductosInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosInventarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosInventarioKeyReleased

    private void txtBuscarInventarioProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarInventarioProdKeyReleased
        buscarInventrarioProducto();
    }//GEN-LAST:event_txtBuscarInventarioProdKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
 habilitarProcesos();      
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblProductosInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosInventarioMouseClicked
        
         
          cargarDatosVentasFormulario("cargarDatos");
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        
        
    }//GEN-LAST:event_tblProductosInventarioMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
//        String rowData[]=new String[3];
//        rowData[0]=lblIdInventario.getText().toString();
//        rowData[1]=lblProducto.getText();
//        rowData[2]=txtCantidad.getText();
//        rowData[3]=lblPrecio.getText();
        
        agregarProducto();
//        this.lblProducto.setText("");
//        this.lblCodigo.setText("");
//        this.lblPrecio.setText("");
//        this.lblStock.setText("");
//        this.lblSub.setText("");
        this.txtCantidad.setText("");
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDetActionPerformed
        eliminarDetalle();
    }//GEN-LAST:event_btnEliminarDetActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
//       if(validar()){
//            Encabezado enc = new Encabezado(Integer.parseInt(lblIdClientess.getText()),Integer.parseInt(lblUsuario.getText()),txtNumeroFactura.getText(), lblFechaActual.getText());
//            enc.guardarEcabezado();
//            
//        }else{
//            System.out.println("Error de validacion, no se creo el registro");
//        }
////       
////           if(validarDetalle()){
////           DetalleFactura deta = new DetalleFactura(Integer.parseInt(lblIdEncabezado.getText()),Integer.parseInt(lblIdInventario.getText()),lblFechaActual.getText(), Double.parseDouble(txtSubtotal.getText()),Double.parseDouble(txtIva.getText()),Double.parseDouble(txtTotal.getText()));
////            deta.guardarDetalle();
////        }else{
////            System.out.println("Error de validacion, no se creo el registro");
////        }
//        agregarDetalle();

            mostrarDatosFacturacion();
            pregunta("Aceptar", "Cancelar");
       
//            actualizarStock();
//             inv.actualizarStock();
        
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cargarDatosFormulario("limpiar");
        cargarDatosVentasFormulario("limpiarProd");
          this.lblProducto.setText("");
        this.lblCodigo.setText("");
        this.lblPrecio.setText("");
        this.lblStock.setText("");
        this.lblSub.setText("");
        this.txtCantidad.setText("");
        this.lblIdInventario.setText("0");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
          if(validar()){
            Encabezado enc = new Encabezado(Integer.parseInt(lblIdClientess.getText()),Integer.parseInt(lblUsuario.getText()),lblNumeroFactura.getText(), lblFechaActual.getText());
            enc.guardarEcabezado();
            
        }else{
            System.out.println("Error de validacion, no se creo el registro");
        }
           agregarDetalle();
//         actualizarStock();
           
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFacturaKeyReleased
        buscarFactura();
    }//GEN-LAST:event_txtBuscarFacturaKeyReleased

    private void btnConsumisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumisorActionPerformed
       this.txtNombreCli.setText("9999999999");
        this.txtCorreo.setText("9999999999");
        this.txtDireccion.setText("9999999999");
        this.txtCedula.setText("9999999999");
        this.txtTelefono.setText("9999999999");
        this.lblIdClientess.setText("9999999999");
    }//GEN-LAST:event_btnConsumisorActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        eliminarFactura();
    }//GEN-LAST:event_btnAnularActionPerformed

    public void buscarCliente() {
        String titulosClientes[] = {"IdCliente", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono","Direccion"};
        dtmClientes.setColumnIdentifiers(titulosClientes);

        Clientes cli = new Clientes();
        
        busqueda = txtBuscar.getText();
        if (rbtnIdCliente.isSelected()) {
            criterio = "IDCLIENTE";
        }else if (rbtnApellido.isSelected()) {
            criterio = "apellidos";
        } else if (rbtnNombre.isSelected()) {
            criterio = "nombres";
        } else if (rbtnCedula.isSelected()) {
            criterio = "cedula";
        }
        try {
            rs = cli.listarClientesPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[7];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmClientes.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmClientes.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);

                dtmClientes.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

           f = dtmClientes.getRowCount();
            lblTotalRegistros.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblClientes.setModel(dtmClientes);
    }

public void cargarDatosVentasFormulario(String msj){
//    int fila = tblProductosInventario.getSelectedRow();
  if (msj.equals("limpiarProd")) {
            inv = new Inventario();
//            prod=new Productos();
        } else if(msj.equals("cargarDatos")){
            Integer fila = tblProductosInventario.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
    }else{
        dtmInventarioProd = (DefaultTableModel) tblProductosInventario.getModel();
        inv.setIdInventario(Integer.parseInt((String)dtmInventarioProd.getValueAt(fila, 0)));
        prod.setDescripcion((String) dtmInventarioProd.getValueAt(fila, 1));
        prod.setCodigo((String) dtmInventarioProd.getValueAt(fila, 2));
        inv.setStock(Integer.parseInt((String) dtmInventarioProd.getValueAt(fila, 4)));
        inv.setPrecio(Double.parseDouble((String) dtmInventarioProd.getValueAt(fila, 5)));
   
        lblIdInventario.setText(inv.getIdInventario().toString());
        lblProducto.setText(prod.getDescripcion());
        lblCodigo.setText(prod.getCodigo());
        lblPrecio.setText(inv.getPrecio().toString());
       lblStock.setText(inv.getStock().toString());
        lblSub.setText(inv.getPrecio().toString());

    
    
  
    
    
 }
        }
        



}



public void cargarDatosFormulario(String msj) {

        if (msj.equals("limpiar")) {
            cli = new Clientes();
        } else if(msj.equals("cargarDatos")){
            Integer fila = tblClientes.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            } else {
                dtmClientes = (DefaultTableModel) tblClientes.getModel();
                cli = new Clientes(Integer.parseInt(dtmClientes.getValueAt(fila, 0).toString()),
                        (String) dtmClientes.getValueAt(fila, 1),
                        (String) dtmClientes.getValueAt(fila, 2),
                        (String) dtmClientes.getValueAt(fila, 3),
                        (String) dtmClientes.getValueAt(fila, 4),
                        (String) dtmClientes.getValueAt(fila, 5),
                        (String) dtmClientes.getValueAt(fila, 6));
            }

        }
        System.out.println(cli.mostrarDatos());
        lblIdClientess.setText(cli.getIdCliente().toString());
        txtNombreCli.setText(cli.getApellidos()+" , "+cli.getNombres());
        txtCedula.setText(cli.getCedula());
        txtCorreo.setText(cli.getCorreo());
        txtTelefono.setText(cli.getTelefono());
        txtDireccion.setText(cli.getDireccion());

}


public void buscarInventrarioProducto() {
        String titulosInventarioProd[] = {"IdInventario", "Descripcion", "Codigo", "Unidad de Medida", "Stock", "Precio"};
        dtmInventarioProd.setColumnIdentifiers(titulosInventarioProd);

        Inventario invP = new Inventario();
        
        
        busqueda = txtBuscarInventarioProd.getText();
        if (rbtnIdInventario.isSelected()) {
            criterio = "idInventario";
        }else if (rbtnDescripcion.isSelected()) {
            criterio = "descripcion";
        } else if (rbtnCodigo.isSelected()) {
            criterio = "codigo";
       
        }
        try {
            rs = invP.listarInventarioProductoPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[6];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmInventarioProd.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmInventarioProd.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                

                dtmInventarioProd.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

            f = dtmInventarioProd.getRowCount();
           lblTotalRegistrosPro.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblProductosInventario.setModel(dtmInventarioProd);
    }


private double redondear(double num){
        return Math.rint(num*100)/100;
    }
    private void calTot(){
        double S=0,iva,tot;
        for(int i=0;i<tblDetalleFactura.getRowCount();i++){
                S=S+Double.parseDouble(dtmDetalleFactura.getValueAt(i, 5).toString());
            }
            S=redondear(S);
            lblSubtotal.setText(String.valueOf(S));
            iva=0.12*S;
            iva=redondear(iva);
            tot=S+iva;
            tot=redondear(tot);
            lblIva.setText(String.valueOf(iva));
            lblTotal.setText(String.valueOf(tot));
    }

public void agregarProducto() {
        dtmDetalleFactura = (DefaultTableModel) tblDetalleFactura.getModel();
       double iva=0;
        int item;
        int contador = 0;
        double total,Sub=0;
        item = contador + 1;
        String idInventario = lblIdInventario.getText();
        String nombreProducto = lblProducto.getText();
        String codigo = lblCodigo.getText();
        precio = Double.parseDouble(lblPrecio.getText());
        cantidad = Integer.parseInt(txtCantidad.getText());
        int stock = Integer.parseInt(lblStock.getText());
        Sub = cantidad * precio;
         iva=Sub*12/100;
         total=Sub+iva;
//        for(int i=0;i<tblDetalleFactura.getRowCount();i++){
//                Sub=Sub+Double.parseDouble(dtmDetalleFactura.getValueAt(i, 7).toString());
//            }
        ArrayList listaFactura = new ArrayList();
        if (stock > 0) {
            listaFactura.add(idInventario);
            listaFactura.add(nombreProducto);
            listaFactura.add(codigo);
            listaFactura.add(cantidad);
            listaFactura.add(precio);
            listaFactura.add(stock);
            listaFactura.add(Sub);
            listaFactura.add(iva);
            listaFactura.add(total);
            Object[] ob = new Object[9];
            ob[0] = listaFactura.get(0);
            ob[1] = listaFactura.get(1);
            ob[2] = listaFactura.get(2);
            ob[3] = listaFactura.get(3);
            ob[4] = listaFactura.get(4);
            ob[5]=  listaFactura.get(5);
            ob[6]=  listaFactura.get(6);
            ob[7]=  listaFactura.get(7);
            ob[8]=  listaFactura.get(8);
            
            dtmDetalleFactura.addRow(ob);
            tblDetalleFactura.setModel(dtmDetalleFactura);


         calTot();
        } else {
            JOptionPane.showMessageDialog(this, "producto no disponible");
        }
    }

// private void eliminarFactura(){
//       int fil;
//       if ( dtmFactura.getRowCount()>0){
//           if (tblFactura.getSelectedRow()!=-1){
//               fil=tblFactura.getSelectedRow();
//                dtmFactura.removeRow(fil);
//               calTot();
//           }else{
//               JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
//           }
//       }else{ JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");}
//    }
   private void eliminarFactura(){
       int fila;
       if (  dtmFactura.getRowCount()>0){
           if (tblFactura.getSelectedRow()!=-1){
               fila=tblFactura.getSelectedRow();
                dtmFactura.removeRow(fila);

           }else{
               JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
           }
       }else{ JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");}
    }

    private void eliminarDetalle(){
       int fila;
       if ( dtmDetalleFactura.getRowCount()>0){
           if (tblDetalleFactura.getSelectedRow()!=-1){
               fila=tblDetalleFactura.getSelectedRow();
                dtmDetalleFactura.removeRow(fila);
              
           }else{
               JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
           }
       }else{ JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");}
    }
    
  public void agregarDetalle() {
        det = new DetalleFactura(
                Integer.parseInt(lblIdEncabezado.getText()),
                Integer.parseInt(lblIdInventario.getText()),
                lblFechaActual.getText(),
                Double.parseDouble(lblSubtotal.getText()),
                Double.parseDouble(lblIva.getText()),
                Double.parseDouble(lblTotal.getText()));
        det.guardarDetalle();
    }
  
  
  public void buscarFactura() {
        String titulosFactura[] = {"IdEncabezado", "IdClientes","Apellido","Nombre", "IdUsuario", "Numero Factura", "Fecha", "Total"};
        dtmFactura.setColumnIdentifiers(titulosFactura);

        Facturacion fac = new Facturacion();
        
        busqueda = txtBuscarFactura.getText();
        if (rbtnIdEncabezado.isSelected()) {
            criterio = "IDENCABEZADO";
        }else if (rbtnCliente.isSelected()) {
            criterio = "IDCLIENTES";
             }else if (rbtnApellidos.isSelected()) {
            criterio = "APELLIDOS";
        } else if (rbtnNumeroFactu.isSelected()) {
            criterio = "ENCNUMEROFACTURA";
        
        }
        try {
            rs = fac.listarFACTURAPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmFactura.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmFactura.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);
                datos[7] = (String) rs.getString(8);
                

                dtmFactura.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

            f = dtmFactura.getRowCount();
           lblTotalFactura.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblFactura.setModel(dtmFactura);
    }
  
//  private void actualizarStock(){
//    
//    for (int i = 0; i < tblDetalleFactura.getRowCount(); i++) {
//        
//        Productos pr=new Productos();
//        Inventario in=new Inventario();
//        Facturacion fac=new Facturacion();
//         idInventario=Integer.parseInt(tblDetalleFactura.getValueAt(i, 0).toString());
//         cantidad=Integer.parseInt(tblDetalleFactura.getValueAt(i, 3).toString());
//        in=inv.listarID(idInventario);
//        int stockActual = inv.getStock() - cantidad;
//        inv.actualizarStock(stockActual, idInventario);
//        
//       
//    }
//}

    public String mostrarDatosFacturacion() {
        String msj;
        msj = ("\n\nIdCliente: " + txtNombreCli.getText()
                + "\nIdUsuario: " + lblUsuario.getText()
                + "\nNumero de Factura: " + lblNumeroFactura.getText()
                + "\nFecha: " + lblFechaActual.getText()
                + "\nSubtotal: " + lblSubtotal.getText()
                + "\nIva: " + lblIva.getText()
                + "\nTotal: "       + lblTotal.getText()
                );
        return msj;
    }
       
       
 public Integer pregunta(String msj1, String msj2) {
        Object[] options = {"Aceptar", "Cancelar"};
        Integer n = JOptionPane.showOptionDialog(null,
                msj1 + mostrarDatosFacturacion(),
                msj2,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        return n;
    }
    
 void generarSerie(){
     String serie=enc.NmeroEnvabezado();
     if(serie==null){
         lblIdEncabezado.setText("24");
     }else{
         Integer increment=Integer.parseInt(serie);
         increment = increment + 1;
         lblIdEncabezado.setText(""+increment);
     }
 }
void SerieNumFactura(){
     String serie=enc.NmeroFactura();
     if(serie==null){
         lblNumeroFactura.setText("4");
     }else{
         Integer increment=Integer.parseInt(serie);
         increment = increment + 1;
         lblNumeroFactura.setText(""+increment);
     }
 }
 
 public void habilitarBotonesInicio(){
        
        btnNuevo.setEnabled(true);
        txtNombreCli.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtDireccion.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        btnSalir.setEnabled(true);
        txtCedula.setEnabled(false);
       txtTelefono.setEnabled(false);
        txtCantidad.setEnabled(false);
        btnAnular.setEnabled(false);
        btnConsumisor.setEnabled(false);
        btnVender.setEnabled(false);
        btnImprimir.setEnabled(false);
        btnCorreo.setEnabled(false);        
        lblProducto.setEnabled(false);
        lblCodigo.setEnabled(false);
        lblPrecio.setEnabled(false);
         lblSub.setEnabled(false);       
         lblStock.setEnabled(false);       
         lblIdInventario.setEnabled(false);
         btnAgregar.setEnabled(false);
         btnEliminarDet.setEnabled(false);
    }

public void habilitarProcesos(){
        
        btnNuevo.setEnabled(true);
        txtNombreCli.setEnabled(true);
        txtCorreo.setEnabled(true);
        txtDireccion.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnSalir.setEnabled(true);
        txtCedula.setEnabled(true);
       txtTelefono.setEnabled(true);
        txtCantidad.setEnabled(true);
         btnAnular.setEnabled(true);
        btnConsumisor.setEnabled(true);
        btnVender.setEnabled(true);
        btnImprimir.setEnabled(true);
        btnCorreo.setEnabled(true);        
        lblProducto.setEnabled(true);
        lblCodigo.setEnabled(true);
        lblPrecio.setEnabled(true);
         lblSub.setEnabled(true);       
         lblStock.setEnabled(true);       
         lblIdInventario.setEnabled(true);
         btnAgregar.setEnabled(true);
         btnEliminarDet.setEnabled(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnConsumisor;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnEliminarDet;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblIdClientess;
    private javax.swing.JLabel lblIdEncabezado;
    private javax.swing.JLabel lblIdInventario;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalFactura;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JLabel lblTotalRegistrosPro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioDatos;
    private javax.swing.JPanel pFormularioDatos;
    private javax.swing.JPanel pFormularioProduc;
    private javax.swing.JRadioButton rbtnApellido;
    private javax.swing.JRadioButton rbtnApellidos;
    private javax.swing.JRadioButton rbtnCedula;
    private javax.swing.JRadioButton rbtnCliente;
    private javax.swing.JRadioButton rbtnCodigo;
    private javax.swing.JRadioButton rbtnDescripcion;
    private javax.swing.JRadioButton rbtnIdCliente;
    private javax.swing.JRadioButton rbtnIdEncabezado;
    private javax.swing.JRadioButton rbtnIdInventario;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnNumeroFactu;
    private javax.swing.ButtonGroup rbtngClientes;
    private javax.swing.ButtonGroup rbtngFactura;
    private javax.swing.ButtonGroup rbtngProductosInventario;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblDetalleFactura;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTable tblProductosInventario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarFactura;
    private javax.swing.JTextField txtBuscarInventarioProd;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
