/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.deu.intsuperior.vista;

import java.sql.ResultSet;
import java.text.ParseException;
//import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ec.edu.intsuperior.modelo.Inventario;
import ec.edu.intsuperior.modelo.Productos;
import ec.edu.intsuperior.modelo.Proveedores;


import static ec.deu.intsuperior.vista.jifrmClientess.rs;
import static ec.deu.intsuperior.vista.jifrmProductos.rs;
import static ec.deu.intsuperior.vista.jifrmProveedores.rs;

/**
 *
 * @author Usuario
 */
public class jifrmInventario extends javax.swing.JInternalFrame {
 String titulos[] = {"idInventario", "idProducto", "idProveedor", "Fecha Compra", "Fecha Elaboracion", "Fecha Expiracion", "Stock","Precio"};

    DefaultTableModel dtm = new DefaultTableModel(null, titulos) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String criterio, busqueda, strCodigo;
    Integer busquedaInt;
    static ResultSet rs = null;
    
      String titulosS[] = {"idProveedor", "Nombre", "Nombre Contacto", "RUC", "Correo", "Telefono", "Direccion","PaginaWeb"};

    DefaultTableModel dtmL = new DefaultTableModel(null, titulosS) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

       String tituloOs[] = {"idProducto", "Descripcion", "Codigo", "Unidad de Medida", "Informacion Nutricional", "ObservacionN"};

    DefaultTableModel dtmt = new DefaultTableModel(null, tituloOs) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    
    
    
    Proveedores pro=new Proveedores();
    Inventario inv = new Inventario();
    Productos prod=new Productos();
    
    
    public jifrmInventario() {
        initComponents();
        rbIdProducto.setSelected(true);
        rbIdProveedor.setSelected(true);
          rbIdInventario.setSelected(true);
//      columnasAutoAjustable(tblCliente); 
      buscarProducto();
      buscarProveedor();
      buscarInventario();
      habilitarBotonesInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgInventarioBus = new javax.swing.ButtonGroup();
        btgProveedor = new javax.swing.ButtonGroup();
        btgProducto = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        pFormularioDatos = new javax.swing.JPanel();
        jcFechaCompra = new com.toedter.calendar.JDateChooser();
        lblIdInventario = new javax.swing.JLabel();
        lblInfoProducto = new javax.swing.JLabel();
        lblInfoProveedores = new javax.swing.JLabel();
        jcFechaElaboracion = new com.toedter.calendar.JDateChooser();
        jcFechaExpiracion = new com.toedter.calendar.JDateChooser();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbIdProducto = new javax.swing.JRadioButton();
        rbDescripcion = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        rbUnidadMedida = new javax.swing.JRadioButton();
        txtProductoBuscar = new javax.swing.JTextField();
        lblTotalProductos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rbIdProveedor = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbRuc = new javax.swing.JRadioButton();
        txtProveedorBuscar = new javax.swing.JTextField();
        lblTotalProveedor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rbIdInventario = new javax.swing.JRadioButton();
        rbProducto = new javax.swing.JRadioButton();
        rbProveedor = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        lblTotalRegistros = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();

        jToolBar1.setBackground(new java.awt.Color(153, 153, 255));
        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarmmmmmm.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirrrrr.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        pFormularioDatos.setBackground(new java.awt.Color(255, 204, 204));

        jcFechaCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Compra"));

        lblIdInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Inventario"));
        lblIdInventario.setOpaque(true);

        lblInfoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de Productos"));
        lblInfoProducto.setOpaque(true);

        lblInfoProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de Proveedores"));
        lblInfoProveedores.setOpaque(true);

        jcFechaElaboracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Elaboracion"));

        jcFechaExpiracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Expiracion"));

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        javax.swing.GroupLayout pFormularioDatosLayout = new javax.swing.GroupLayout(pFormularioDatos);
        pFormularioDatos.setLayout(pFormularioDatosLayout);
        pFormularioDatosLayout.setHorizontalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInfoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcFechaExpiracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcFechaElaboracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(jcFechaCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pFormularioDatosLayout.createSequentialGroup()
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pFormularioDatosLayout.setVerticalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.addTab("Formulario deDatos", pFormularioDatos);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        btgProducto.add(rbIdProducto);
        rbIdProducto.setText("Id Producto");

        btgProducto.add(rbDescripcion);
        rbDescripcion.setText("Descripcion");

        btgProducto.add(rbCodigo);
        rbCodigo.setText("Codigo");

        btgProducto.add(rbUnidadMedida);
        rbUnidadMedida.setText("Unidad de Medida");

        txtProductoBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Texto de Busqueda"));
        txtProductoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductoBuscarKeyReleased(evt);
            }
        });

        lblTotalProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("    Total de Registros"));
        lblTotalProductos.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbIdProducto)
                        .addGap(18, 18, 18)
                        .addComponent(rbDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(rbCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(rbUnidadMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbIdProducto)
                        .addComponent(rbDescripcion)
                        .addComponent(rbCodigo)
                        .addComponent(rbUnidadMedida))
                    .addComponent(lblTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(txtProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblProducto.setBackground(new java.awt.Color(204, 204, 255));
        tblProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Producto", jPanel2);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        btgProveedor.add(rbIdProveedor);
        rbIdProveedor.setText("Id Proveedor");

        btgProveedor.add(rbNombre);
        rbNombre.setText("Nombre");

        btgProveedor.add(rbRuc);
        rbRuc.setText("RUC");

        txtProveedorBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el texto de Busqueda"));
        txtProveedorBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProveedorBuscarKeyReleased(evt);
            }
        });

        lblTotalProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("     Total de Registros"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtProveedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbIdProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(rbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbRuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbIdProveedor)
                            .addComponent(rbNombre)
                            .addComponent(rbRuc)))
                    .addComponent(lblTotalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtProveedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153)));
        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProveedor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Proveedor", jPanel3);

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        btgInventarioBus.add(rbIdInventario);
        rbIdInventario.setText("Id Inventario");

        btgInventarioBus.add(rbProducto);
        rbProducto.setText("Producto");

        btgInventarioBus.add(rbProveedor);
        rbProveedor.setText("Proveedor");

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Texto de Busqueda"));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        lblTotalRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("     Total Registros"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(rbIdInventario)
                        .addGap(18, 18, 18)
                        .addComponent(rbProducto)
                        .addGap(18, 18, 18)
                        .addComponent(rbProveedor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIdInventario)
                    .addComponent(rbProducto)
                    .addComponent(rbProveedor))
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        tblInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblInventarioKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblInventario);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Inventario", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbDatos)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbDatos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      buscarInventario();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtProveedorBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorBuscarKeyReleased
         buscarProveedor();
    }//GEN-LAST:event_txtProveedorBuscarKeyReleased

    private void txtProductoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoBuscarKeyReleased
        buscarProducto();
    }//GEN-LAST:event_txtProductoBuscarKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         inv.eliminar();
       buscarInventario();
       habilitarBotonesInicio();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
          cargarDatosProductosFormulario();
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
      
    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
         String fechaCompra, fechaElaboracion,fechaExpiracion;
        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
        
        inv = new Inventario(prod.getIdProducto(),pro.getIdProveedor(),fechaCompra,fechaElaboracion,fechaExpiracion,Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));
        inv.guardar();
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInventarioKeyReleased
           habilitarBotonesProceso();
    }//GEN-LAST:event_tblInventarioKeyReleased

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        cargarDatosProveedoresFormulario();
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
       
    }//GEN-LAST:event_tblProveedorMouseClicked

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
     try {
         cargarDatosInventarioFormulario("cargarDatos");
     } catch (ParseException ex) {
         Logger.getLogger(jifrmInventario.class.getName()).log(Level.SEVERE, null, ex);
     }
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        habilitarBotonesProceso();
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String fechaCompra, fechaElaboracion,fechaExpiracion;
          fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());

        inv = new Inventario(Integer.parseInt(lblIdInventario.getText()),Integer.parseInt(lblInfoProducto.getText()),Integer.parseInt(lblInfoProveedores.getText()), fechaCompra,fechaElaboracion, fechaExpiracion,Integer.parseInt(txtStock.getText()),Double.parseDouble( txtPrecio.getText()));
       inv.actualizar();
       buscarInventario();
       habilitarBotonesInicio();
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       habilitarBotonesProcesoCargar();
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
//     try {
//         cargarDatosInventarioFormulario("limpiar");
//     } catch (ParseException ex) {
//         Logger.getLogger(jifrmInventario.class.getName()).log(Level.SEVERE, null, ex);
//     }
        habilitarBotonesInicio();
        
           this.lblIdInventario.setText("");
       this.lblInfoProducto.setText("");
       this.lblInfoProveedores.setText("");
       this.jcFechaCompra.setDateFormatString("");
       this.jcFechaElaboracion.setDateFormatString("");
       this.jcFechaExpiracion.setDateFormatString("");
                       this.txtStock.setText("");
                               this.txtPrecio.setText("");
       
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarBotonesInicio();
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed
public void buscarInventario() {
        String titulos[] = {"IdInventario", "IdProductos", "IdProveedores", "Fecha Compra", "Fecha Elaboracion", "Expiracion","Stock","Precio"};
        dtm.setColumnIdentifiers(titulos);

        Inventario inv = new Inventario();
        
        busqueda = txtBuscar.getText();
        if (rbIdInventario.isSelected()) {
            criterio = "idInventario";
        }else if (rbProducto.isSelected()) {
            criterio = "idProducto";
        } else if (rbProveedor.isSelected()) {
            criterio = "idProveedor";
        
        }
        try {
            rs = inv.listarInventarioPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtm.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtm.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);
                datos[7] = (String) rs.getString(8);

                dtm.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

            f = dtm.getRowCount();
            lblTotalRegistros.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblInventario.setModel(dtm);
    }

public void buscarProveedor() {
        String titulosS[] = {"IdProveedor", "Nombres", "Nombre de Contacto", "RUC", "Correo", "Telefono","Direccion", "Pagina Web"};
        dtmL.setColumnIdentifiers(titulosS);

        Proveedores prov = new Proveedores();
        
        busqueda = txtProveedorBuscar.getText();
        if (rbIdProveedor.isSelected()) {
            criterio = "idProveedor";
        }else if (rbNombre.isSelected()) {
            criterio = "nombres";
       
        } else if (rbRuc.isSelected()) {
            criterio = "ruc";
        }
        try {
            rs = prov.listarProveedoresPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmL.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmL.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);
                datos[7] = (String) rs.getString(8);
                dtmL.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }
               f = dtmL.getRowCount();
            lblTotalProveedor.setText(String.valueOf(f));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblProveedor.setModel(dtmL);
    }

public void buscarProducto() {
        String tituloOs[] = {"IdProducto", "Descripcion", "Codigo", "Unidad de Medida", "Informacion Nutricional", "Observacion"};
        dtmt.setColumnIdentifiers(tituloOs);

        Productos pro = new Productos();
        
        busqueda = txtProductoBuscar.getText();
        if (rbIdProducto.isSelected()) {
            criterio = "idProducto";
        }else if (rbDescripcion.isSelected()) {
            criterio = "descripcion";
        } else if (rbCodigo.isSelected()) {
            criterio = "codigo";
        } else if (rbUnidadMedida.isSelected()) {
            criterio = "unidadMedida";
        }
        try {
            rs = pro.listarProductosPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[6];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmt.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmt.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);

                dtmt.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

               f = dtmt.getRowCount();
            lblTotalProductos.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblProducto.setModel(dtmt);
    }

public void cargarDatosProductosFormulario(){
    int fila = tblProducto.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
    }else{
        dtmt = (DefaultTableModel) tblProducto.getModel();
        prod.setIdProducto(Integer.parseInt((String)dtmt.getValueAt(fila, 0)));
        prod.setDescripcion((String) dtmt.getValueAt(fila, 1));
        prod.setCodigo((String) dtmt.getValueAt(fila, 2));
        prod.setUnidadMedida((String) dtmt.getValueAt(fila, 3));
        
        
        lblInfoProducto.setText(prod.getIdProducto()+" , "+prod.getDescripcion()+" , "+prod.getCodigo()+" , "+prod.getUnidadMedida());

    }
}

public void cargarDatosProveedoresFormulario(){
    int fila = tblProveedor.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
    }else{
        dtmL = (DefaultTableModel) tblProveedor.getModel();
        pro.setIdProveedor(Integer.parseInt((String)dtmL.getValueAt(fila, 0)));
        pro.setNombre((String) dtmL.getValueAt(fila, 1));
        pro.setNomContacto((String) dtmL.getValueAt(fila, 2));
        pro.setRuc((String) dtmL.getValueAt(fila, 3));
        
        
        lblInfoProveedores.setText(pro.getIdProveedor()+" , "+pro.getNombre()+" , "+pro.getNomContacto()+" , "+pro.getRuc());

    }
}

public void cargarDatosInventarioFormulario(String msj) throws ParseException {
//    int fila = tblInventario.getSelectedRow();
    
 if (msj.equals("limpiar")) {
            inv = new Inventario();
        } else if(msj.equals("cargarDatos")){
            Integer fila = tblInventario.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
    }else{
        dtm = (DefaultTableModel) tblInventario.getModel();
        inv.setIdInventario(Integer.parseInt((String)dtm.getValueAt(fila, 0)));
        inv.setIdProducto(Integer.parseInt((String)dtm.getValueAt(fila, 1)));
        inv.setIdProveedor(Integer.parseInt((String)dtm.getValueAt(fila, 2)));
        inv.setFechaCompra((String) dtm.getValueAt(fila, 3));
        inv.setFechaElaboracion((String) dtm.getValueAt(fila, 4));
        inv.setFechaExpiracion((String) dtm.getValueAt(fila, 5));
        inv.setStock(Integer.parseInt((String)dtm.getValueAt(fila, 6)));
        inv.setPrecio(Double.parseDouble((String)dtm.getValueAt(fila, 7)));
      
    }
        }
 
         System.out.println(inv.mostrarDatos());
         
        lblIdInventario.setText(inv.getIdInventario().toString());
        lblInfoProducto.setText(inv.getIdProducto().toString());
        lblInfoProveedores.setText(inv.getIdProveedor().toString());
        jcFechaCompra.setDate(formatoFecha.parse(inv.getFechaCompra()));
        jcFechaElaboracion.setDate(formatoFecha.parse(inv.getFechaElaboracion()));
        jcFechaExpiracion.setDate(formatoFecha.parse(inv.getFechaExpiracion()));
        txtStock.setText(inv.getStock().toString());
        txtPrecio.setText(inv.getPrecio().toString());
       
        strCodigo = (inv.getIdInventario().toString());
        
        
//        lblInfoProveedores.setText(pro.getIdProveedor()+" , "+pro.getNombre()+" , "+pro.getNomContacto()+" , "+pro.getRuc());

    
}


 public void habilitarBotonesProceso(){
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        btnSalir.setEnabled(true);
        //habilita las cajas de texto del formulario 
        lblIdInventario.setEnabled(true);
        lblInfoProducto.setEnabled(true);
        lblInfoProveedores.setEnabled(true);
        jcFechaCompra.setEnabled(true);
        jcFechaElaboracion.setEnabled(true);
        jcFechaExpiracion.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        
    }
     public void habilitarBotonesInicio(){
        //habilita o desabilita los botones del menu
         btnNuevo.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnSalir.setEnabled(true);
        //bloquea las cajas de texto del formulario 
        lblIdInventario.setEnabled(false);
        lblInfoProducto.setEnabled(false);
        lblInfoProveedores.setEnabled(false);
        jcFechaCompra.setEnabled(false);
        jcFechaElaboracion.setEnabled(false);
        jcFechaExpiracion.setEnabled(false);
        txtStock.setEnabled(false);
        txtPrecio.setEnabled(false);
    }
     public void habilitarBotonesProcesoCargar(){
        //habilita o desabilita los botones del menu
          btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnSalir.setEnabled(true);
        //habilita las cajas de texto del formulario 
        lblIdInventario.setEnabled(true);
        lblInfoProducto.setEnabled(true);
        lblInfoProveedores.setEnabled(true);
        jcFechaCompra.setEnabled(true);
        jcFechaElaboracion.setEnabled(true);
        jcFechaExpiracion.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgInventarioBus;
    private javax.swing.ButtonGroup btgProducto;
    private javax.swing.ButtonGroup btgProveedor;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private com.toedter.calendar.JDateChooser jcFechaCompra;
    private com.toedter.calendar.JDateChooser jcFechaElaboracion;
    private com.toedter.calendar.JDateChooser jcFechaExpiracion;
    private javax.swing.JLabel lblIdInventario;
    private javax.swing.JLabel lblInfoProducto;
    private javax.swing.JLabel lblInfoProveedores;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JLabel lblTotalProveedor;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JPanel pFormularioDatos;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbDescripcion;
    private javax.swing.JRadioButton rbIdInventario;
    private javax.swing.JRadioButton rbIdProducto;
    private javax.swing.JRadioButton rbIdProveedor;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JRadioButton rbProducto;
    private javax.swing.JRadioButton rbProveedor;
    private javax.swing.JRadioButton rbRuc;
    private javax.swing.JRadioButton rbUnidadMedida;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProductoBuscar;
    private javax.swing.JTextField txtProveedorBuscar;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
