/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.deu.intsuperior.vista;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ec.edu.intsuperior.modelo.Empleados;
import ec.edu.intsuperior.modelo.usuarios;

import static ec.deu.intsuperior.vista.jifrmClientess.rs;
import static ec.deu.intsuperior.vista.jifrmEmpleados.rs;

/**
 *
 * @author Usuario
 */
public class jifrmUsuarios extends javax.swing.JInternalFrame {

    
   String titulos[] = {"idUusuario", "IdEmpleado", "Usuario", "FechaCreacion"};

    DefaultTableModel dtm = new DefaultTableModel(null, titulos) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

      String titulosEmpleados[] = {"idEmpledo", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono", "Direccion"};

    DefaultTableModel dtmEmpleado = new DefaultTableModel(null, titulosEmpleados) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
   
    String criterio, busqueda, strCodigo;
    Integer busquedaInt;
    static ResultSet rs = null;
    usuarios usu = new usuarios();
     Empleados emp = new Empleados();
     
     
 
    
    public jifrmUsuarios() {
        initComponents();
        lblFechaActual.setText(fechaActual());
        rbtnIdEmpleado.setSelected(true);
         rbtnIdUsuario.setSelected(true);
         buscarUsuario();
         buscarEmpleado();
         lblPaUsuario.setText(usu.getUsuUsuario());
    }

      public jifrmUsuarios(usuarios usu) {
        initComponents();
         lblPaUsuario.setText(usu.getUsuUsuario());
         this.usu=usu;
        lblFechaActual.setText(fechaActual());
        rbtnIdEmpleado.setSelected(true);
         rbtnIdUsuario.setSelected(true);
         buscarUsuario();
         buscarEmpleado();
        
    }

    
     public static String fechaActual(){
    
    Date fecha=new Date();
    SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy-MM-dd");
    
    return formatoFecha.format(fecha);
    
}

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngUsuarios = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        pFormularioDatos = new javax.swing.JPanel();
        lblIdUsuario = new javax.swing.JLabel();
        lblInfoEmpleado = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pswClave = new javax.swing.JPasswordField();
        lblPaUsuario = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbtnIdEmpleado = new javax.swing.JRadioButton();
        rbtnApellido = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnCedula = new javax.swing.JRadioButton();
        txtBuscarEmpleado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        rbtnIdUsuario = new javax.swing.JRadioButton();
        rbtnUsuario = new javax.swing.JRadioButton();
        rbtnPaUsuario = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUusario = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirrrrr.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        lblIdUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Usuario"));

        lblInfoEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));

        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        pswClave.setBorder(javax.swing.BorderFactory.createTitledBorder("Clave"));

        lblPaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("PaUsuario"));

        lblFechaActual.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Actual"));

        javax.swing.GroupLayout pFormularioDatosLayout = new javax.swing.GroupLayout(pFormularioDatos);
        pFormularioDatos.setLayout(pFormularioDatosLayout);
        pFormularioDatosLayout.setHorizontalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pswClave, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                    .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pFormularioDatosLayout.setVerticalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pswClave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        tbDatos.addTab("Formuladio Usuario", pFormularioDatos);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        rbtnIdEmpleado.setText("IdEmpleado");

        rbtnApellido.setText("Apellido");

        rbtnNombre.setText("Nombre");

        rbtnCedula.setText("Cedula");

        txtBuscarEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Criterio de Busqueda"));
        txtBuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEmpleadoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnIdEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnApellido)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCedula)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdEmpleado)
                    .addComponent(rbtnApellido)
                    .addComponent(rbtnNombre)
                    .addComponent(rbtnCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        tblEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblEmpleadosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbDatos.addTab("Buscar Empleado", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Criterio de Busqueda"));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        rbtngUsuarios.add(rbtnIdUsuario);
        rbtnIdUsuario.setText("Id Usuario");

        rbtngUsuarios.add(rbtnUsuario);
        rbtnUsuario.setText("Usuario");

        rbtngUsuarios.add(rbtnPaUsuario);
        rbtnPaUsuario.setText("PaUsuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbtnIdUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnPaUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdUsuario)
                    .addComponent(rbtnUsuario)
                    .addComponent(rbtnPaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tblUusario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUusario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("Buscar Usuario", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbDatos)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
         buscarUsuario();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEmpleadoKeyReleased
       buscarEmpleado();
    }//GEN-LAST:event_txtBuscarEmpleadoKeyReleased

    private void tblEmpleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEmpleadosKeyReleased
       
    }//GEN-LAST:event_tblEmpleadosKeyReleased

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
         cargarDatoEmpleadosFormulario();
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//       String fechaCreacion;
//        fechaCreacion = formatoFecha.format(lblFechaActual.setText(fechaActual()));
        
         usu = new usuarios(emp.getIdEmpleado(),txtUsuario.getText(),pswClave.getText(),lblPaUsuario.getText(),lblFechaActual.getText());
        usu.guardar();
               
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          usu.eliminarUsuario();
       buscarUsuario();
//       habilitarBotonesInicio();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
public void buscarUsuario() {
        String titulos[] = {"IdUsuario", "IdEmpleado", "Usuario", "FechaUsuario"};
        dtm.setColumnIdentifiers(titulos);

        usuarios usu = new usuarios();
        
        busqueda = txtBuscar.getText();
        if (rbtnIdUsuario.isSelected()) {
            criterio = "IDUSUARIO";
        }else if (rbtnUsuario.isSelected()) {
            criterio = "USUUSUARIO";
//        }else if (rbtnPaUsuario.isSelected()) {
//            criterio = "PAUSUARIO";
        }
        try {
            rs = usu.listarUsuarioPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[4];
            //Borrar registros de dtm existes
            int f, i;
            f = dtm.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtm.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(6);
                
                

                dtm.addRow(datos);
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

//            f = dtm.getRowCount();
//            lblTotalRegistros.setText(String.valueOf(f));
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblUusario.setModel(dtm);
    }

public void buscarEmpleado() {
        String titulosEmpleados[] = {"IdEmpleado", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono","Direccion", "Cargo"};
        dtmEmpleado.setColumnIdentifiers(titulosEmpleados);

        Empleados emp = new Empleados();
        
        busqueda = txtBuscar.getText();
        if (rbtnIdEmpleado.isSelected()) {
            criterio = "idEmpledo";
        }else if (rbtnApellido.isSelected()) {
            criterio = "nombres";
        } else if (rbtnNombre.isSelected()) {
            criterio = "apellidos";
        } else if (rbtnCedula.isSelected()) {
            criterio = "cedula";
        }
        try {
            rs = emp.listarEmpleadosPorParametro(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmEmpleado.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmEmpleado.removeRow(0);
                }
            }
            while (rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);
                datos[7] = (String) rs.getString(8);
                
                dtmEmpleado.addRow(datos);
                
                encuentra = true;

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }
//   f = dtm.getRowCount();
//            lblTotalRegistros.setText(String.valueOf(f));
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tblEmpleados.setModel(dtmEmpleado);
    }

public void cargarDatoEmpleadosFormulario(){
    int fila = tblEmpleados.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
    }else{
        dtmEmpleado = (DefaultTableModel) tblEmpleados.getModel();
        emp.setIdEmpleado(Integer.parseInt((String)dtmEmpleado.getValueAt(fila, 0)));
        emp.setApellidos((String) dtmEmpleado.getValueAt(fila, 1));
        emp.setNombres((String) dtmEmpleado.getValueAt(fila, 2));
        emp.setCargo((String) dtmEmpleado.getValueAt(fila, 7));
        
        
        lblInfoEmpleado.setText(emp.getIdEmpleado()+" , "+emp.getApellidos()+" , "+emp.getNombres()+" , "+emp.getCargo());
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblInfoEmpleado;
    private javax.swing.JLabel lblPaUsuario;
    private javax.swing.JPanel pFormularioDatos;
    private javax.swing.JPasswordField pswClave;
    private javax.swing.JRadioButton rbtnApellido;
    private javax.swing.JRadioButton rbtnCedula;
    private javax.swing.JRadioButton rbtnIdEmpleado;
    private javax.swing.JRadioButton rbtnIdUsuario;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnPaUsuario;
    private javax.swing.JRadioButton rbtnUsuario;
    private javax.swing.ButtonGroup rbtngUsuarios;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTable tblUusario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarEmpleado;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
